# Generated by Django 4.2 on 2023-04-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_email_alter_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
