# Generated by Django 4.2 on 2023-04-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.TextField()),
            ],
        ),
    ]
