# Generated by Django 4.2 on 2023-04-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_skillupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
